spring:
  config:
    import: optional:configserver:http://${CONFIG_HOST:127.0.0.1}:${CONFIG_PORT:8888}/
  cloud:
    config:
      name: recommendation-service
  application:
    name: recommendation-service
  profiles:
    active: prod
    include:
      - redis
      - security
      - openfeign
      - eureka
      - actuator
      - internal
      - google
