spring:
  config:
    import: optional:configserver:http://${CONFIG_HOST:127.0.0.1}:${CONFIG_PORT:8888}/
  cloud:
    config:
      name: recommendation-service
  application:
    name: recommendation-service
  profiles:
    active: local
    include:
      - datasource
      - security
      - redis
      - api
      - internal